# -*- coding: utf-8 -*-
"""Melñik Micaela- Comision 252561- Analisis de Datos-Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWfyx3vdKB1n2ddBSUkqJiO_W1X8KFcO

# Entrega Final
* **Curso:** Data Analytics con Python
* **Comisión:** 25261
* **Alumno:** Micaela del Pilar Melñik
* **Fecha:** 20/11/2025

# ***Etapa 3***
**Objetivo:** Realizar análisis estadísticos y exploratorios sobre los datos procesados.

* 3.1. Estadística Descriptiva: Calcular medidas de tendencia central y dispersión
sobre las ventas. Presentar los resultados en un informe.
* 3.2. Análisis Exploratorio de Datos (EDA): Realizar un análisis
exploratorio utilizando visualizaciones para identificar patrones y tendencias
en las ventas.
* 3.3. Correlación: Evaluar la relación entre diferentes variables (por ejemplo,
precio y cantidad vendida) y mostrar los resultados en un gráfico.
* 3.4. Consolidación de Datos: Consolidar todos los análisis previos y preparar un
conjunto de datos final que resuma los hallazgos clave para la presentación.

#***Etapa 4***
**Objetivo:** Aprender a visualizar datos de manera efectiva utilizando diversas bibliotecas.
* 4.1. Visualización con Matplotlib: Crear gráficos básicos (líneas, barras,
dispersión) que representen las ventas con diferentes periodos de tiempo.
* 4.2. Visualización Avanzada con Seaborn: Desarrollar visualizaciones
estadísticas avanzadas, utilizando paletas y estilos para mejorar la
presentación.
* 4.3. Visualización Interactiva con Plotly: Construir un dashboard interactivo
que combine múltiples visualizaciones, permitiendo al usuario explorar los
datos dinámicamente.
* 4.4. Presentación Final: Preparar una presentación que resuma los hallazgos,
insights y visualizaciones generadas a lo largo del proyecto. Presentar ante
un panel simulado de "expertos" en SynthData, recibiendo feedback sobre el
trabajo realizado.

# Primero realizo la preparación de datos que realice en las etapas 1 y 2 de la pre-entrega
"""

import pandas as pd
import numpy as np

# ----CARGO LOS DATAFRAMES----
ventas    = pd.read_csv("ventas-1.csv")
clientes  = pd.read_csv("clientes-1.csv")
marketing = pd.read_csv("marketing-1.csv")

#----PRIMERA VISTA DE LOS DATAFRAMES----
print("ventas:", ventas.shape)
print("clientes:", clientes.shape)
print("marketing:", marketing.shape)

# Introducción a Pandas y primer análisis exploratorio

def explorar_inicial(df, nombre):
  print()
  print(f"{nombre.upper()} ") # Hago el nombre en forma de título (mayúscula al principio).

  # ----Tamaño y tipo de dato----
  print("Shape (filas, columnas):", df.shape)
  print("\nTipos de datos:")
  print(df.dtypes) # puedo visualizar los titulos de las columnas y los datos que hay en ellas.

  #----Comprobar valores nulos----
  print()
  print("----Nulos por columna ----")
  print(df.isna().sum()) # compruebo los valores nulos en el df y los sumo

  #----Comprobar duplicados----
  print()
  print("----Duplicados----")
  print(df.duplicated().sum()) # busco los duplicados y los sumo

  # ---- Muestra preliminar del contenido ----
  print()
  print("----Primeras 5 filas----")
  display(df.head(5)) # muestro las primeras 5 filas del df

  # ---- Resumen columnas numericas ----
  num = df.select_dtypes(include="number") # filtra las columnas por tipo de dato, en este caso numero. asi que selecciona las columnas numericas.
  if not num.empty: # si es una columna numerica, sigue el bloque de analisis. en caso contratio muestra un mensaje aclarando que no hay columna numerica
    print("Resumen numérico")
    display(num.describe().T) #genera un resumen estadistico de las columnas numericas. el .T hace que las columnas aparezcan como filas, haciendo mas comoda la lectura.
  else:
    print("No hay columnas numéricas")

  # ---- Resumen columnas categóricas ----
  cate = df.select_dtypes(include="object") # filtra las columnas por tipo de dato, en este caso objeto. selecciona las columnas de tipo objeto
  if not cate.empty: # si es una columna de tipo objeto, sigue el bloque de analisis. en caso contrario, muestra un mensaje aclarando que no hay columna de tipo objeto
    print("Resumen categórico")
    display(cate.describe().T) #genera un resumen de las columnas categoricas. el .T hace que las columnas aparezcan como filas, haciendo mas comoda la lectura.
  else:
    print("No hay columnas categóricas")

explorar_inicial(ventas, "ventas")

# ---- Ahora aplico explorar_inicial con Clientes ----
explorar_inicial(clientes, "clientes") # utilizo el primer codigo pero con el df "clientes"

# ---- Ahora aplico explorar_inicial con Marketing ----
explorar_inicial(marketing, "marketing") # utilizo el primer codigo pero con el df marketing

# ----Control previo----
prev_shape = ventas.shape
prev_nulos_precio   = ventas['precio'].isna().sum() # comprueba si hay nulos, y en caso de que haya los suma
prev_nulos_cantidad = ventas['cantidad'].isna().sum() # comprueba si hay nulos, y en caso de que haya los suma
prev_dup            = ventas.duplicated().sum() # comprueba si hay duplicados, y en caso de que haya los suma

print("----Antes de limpiar Ventas----")
print("shape:", prev_shape,
      "\n  nulos precio:", prev_nulos_precio,
      "\n  nulos cantidad:", prev_nulos_cantidad,
      "\n  duplicados:", prev_dup)

# ----1° paso: Normalizar el precio (de string a float)----
if 'precio' in ventas.columns: # me aseguro que la columna precio este en el df ventas
  ventas['precio'] = (
      ventas['precio']
      .astype(str) # convierto los valores de esta columna a str (texto)
      .str.replace(r'[$,\s]', '', regex=True) # elimino símbolos de moneda, comas, espacios
      .replace({'nan': np.nan}) # reemplaza el nan (en formato de texto) a el NaN de numpy (representa un valor nulo)
      )
  ventas['precio'] = pd.to_numeric(ventas['precio'], errors='coerce') # convierte la cadena de texto ya limpia a formato de numero

# ----- 2° paso: Convertir fechas en "ventas" y "marketing"----
# if 'fecha_venta' in ventas.columns:
 # ventas['fecha_venta'] = pd.to_datetime(ventas['fecha_venta'], dayfirst=True, errors='coerce')
#for col in ['fecha_inicio', 'fecha_fin']:
 #   if col in marketing.columns:
  #      marketing[col] = pd.to_datetime(marketing[col], dayfirst=True, errors='coerce')

# Conversión de fechas
if 'fecha_venta' in ventas.columns: # # me aseguro que la columna fecha_venta este en el df ventas
    ventas['fecha_venta'] = pd.to_datetime(ventas['fecha_venta'], dayfirst=True, errors='coerce') # convierte los valores de esta columna a tipo fecha tipo dd/mm/aa.
                                                                                                  # coerse fuerza que, si hay algún valor inválido (por ejemplo, texto que no parece fecha), Pandas lo convierta en NaT (Not a Time, equivalente a NaN pero para fechas).

for col in ['fecha_inicio', 'fecha_fin']: # bucle que recorre las columnas fecha_inicia y fecha_fin
    if col in marketing.columns: #verifico si la columna existe en el df marketing
        marketing[col] = pd.to_datetime(marketing[col], dayfirst=True, errors='coerce') #Convierte cada columna encontrada (fecha de inicio y fecha de fin de campaña) a tipo datetime, igual que antes.

# Verificación rápida
print("Resumen de conversiones:")
if 'fecha_venta' in ventas.columns:
    print(f"NaT en fecha_venta: {ventas['fecha_venta'].isna().sum()}") # si encuentra NaT en ventas, lo suma.

for col in ['fecha_inicio', 'fecha_fin']:
    if col in marketing.columns:
        print(f"NaT en {col}: {marketing[col].isna().sum()}") # si encuentra NaT en marketing, lo suma.

# ---- 3° paso:Eliminar filas con nulos críticos en "ventas"----
mask_validos = ventas['precio'].notna() & ventas['cantidad'].notna() # me devuelve un valor de tipo booleano (true) si el valor no es nulo
eliminados_nulos = (~mask_validos).sum() # el ~ convierte en lo contrario los valores booleanos (de true a false y viceversa).
                                         # marca las filas que tienen al menos un nulo. suma los valores true.
                                         # guarda cuántas filas con valores nulos fueron detectadas y eliminadas.
print("Eliminados por nulos:", eliminados_nulos)
ventas = ventas[mask_validos].copy() # Usa la máscara para quedarse solo con las filas válidas (las que no tienen nulos en precio ni en cantidad). el .copy sirve para hacer una copia del df
                                     # asi no se pierde el df original

# ----4° paso: Elimino duplicados exactos en ventas----
tamano_antes = len(ventas) # el tamaño del df antes de eliminar los duplicados
ventas = ventas.drop_duplicates().copy() # creo un nuevo df con los valores duplicados eliminados
tamano_despues = len(ventas) # tamaño del df despues de la eliminacion de dupliados
dup_eliminados = tamano_antes - tamano_despues
print("Duplicados eliminados:", dup_eliminados)

# ----5° paso: Creo columna importe para uso posterior----
ventas['importe'] = ventas['precio'] * ventas['cantidad']

# ----6° paso: post-limpieza----
post_shape = ventas.shape
post_nulos_precio   = ventas['precio'].isna().sum()
post_nulos_cantidad = ventas['cantidad'].isna().sum()
post_dup            = ventas.duplicated().sum()

print("----Después de limpiar Ventas----") # muestro que se eliminaros los nulos y duplicados
print("shape:", post_shape,
      "| nulos precio:", post_nulos_precio,
      "| nulos cantidad:", post_nulos_cantidad,
      "| duplicados:", post_dup)

# ----7° paso: Vista rápida----
print("\nChequeo rápido (post-limpieza):")
print("\nnulos importe:", ventas['importe'].isna().sum())
print("\nrango fechas ventas:", ventas['fecha_venta'].min(), "a", ventas['fecha_venta'].max())

# Vista mínima
display(ventas.head(5))

# Script básico que calcula las ventas mensuales


# Aseguro que exista la columna 'importe'
if 'importe' not in ventas.columns:
    ventas['importe'] = ventas['precio'] * ventas['cantidad']

# Creo un diccionario acumulador
totales = {} # esto servira como acumulador donde se iran guardando las ventas totales por año y mes

# Contadores de control
procesadas = 0 # cuenta cuantas filas validas de analizan
omitidas = 0 # cantidad de filas saltadas por datos faltantes

# Recorro el DataFrame fila por fila
for fila in ventas.itertuples(index=False): # recorre le df fila por fila
    fecha = fila.fecha_venta
    importe = fila.importe

 # Valido que la fila tenga datos válidos
    if pd.isna(fecha) or pd.isna(importe): # si hay valores nulos el contador omitidos se incrementa en 1
        omitidas += 1
        continue

    año = fecha.year # a partir del objeto datatime, extraigo el año y mes
    mes = fecha.month # creoclave única combinando ambos valores (año, mes).

    clave = (año, mes) #Esa clave servirá para agrupar las ventas del mismo mes y año.

    # Acumulo los importes por (año, mes)
    if clave in totales:          # Si la clave (año, mes) ya existe en el diccionario totales, se le suma el importe de la fila actual.
        totales[clave] += importe
    else:
        totales[clave] = importe # Si no existe, se crea una nueva entrada con el importe inicial.

    procesadas += 1              # se incrementa el contador de procesadas.

# Ordeno las claves (año, mes)
totales_ordenados = dict(sorted(totales.items())) # el sorted () sirve para ordenar el diccionario por sus claves, haciendo que aparezcan cronologicamente

# Muestro los resultados
print("---- Ventas mensuales ---- \n")
for (año, mes), total in totales_ordenados.items():
    print(f"{año}-{mes:02d}: ${total:,.2f}") # el :02d es para que sean con dos digitos y :,.2f formatea el número con comas para miles y dos decimales.

print("\n---- Resumen ----")
print("Filas procesadas:", procesadas)
print("Filas omitidas por datos faltantes:", omitidas)

# ----Creo una lista vacía donde voy a guardar cada registro de venta----
registros = [] # aqui se guardaran todas las ventas. cada ventase representará con un diccionario individual,
               # que contendrá las claves "producto", "precio" y "cantidad". seria una lista de diccionarios

# Recorro el DataFrame fila por fila
for fila in ventas.itertuples(index=False): # permite recorrer cada fila del DataFrame ventas. uso index_false para omitir el indice

# Armo un diccionario con los datos que quiero guardar
    registro = {
        "producto": fila.producto,                 # nombre del producto
        "precio": float(fila.precio),              # lo convierto a número decimal
        "cantidad": float(fila.cantidad)           # lo convierto a número decimal
    }

# Agrego ese diccionario a la lista general
    registros.append(registro) # Cada diccionario creado se agrega al final de la lista registros.

# ----Resultado----

# Muestro los primeros 10 registros para verificar
print("Registros guardados:")
for r in registros[:10]:
    print(r)

# Compruebo cuántas ventas se guardaron
print("\nTotal de registros almacenados:", len(registros))

# ----Paso 1: Calcular ingresos totales por producto----

# Creé un diccionario acumulador: clave = producto, valor = ingresos totales
ingresos_por_producto = {}

for fila in ventas.itertuples(index=False): # Recorro el df fila por fila. En cada iteración, se extraen los valores de las columnas producto e importe de la fila actual.
    producto = fila.producto
    importe = fila.importe

    if pd.isna(producto) or pd.isna(importe):
        continue  # hago una validación de calidad de datos. omito filas inválidas. si es NaN omito esa fila y paso a la siguiente

    if producto in ingresos_por_producto: # Si el producto ya existe como clave en el diccionario, se suma su nuevo importe al total acumulado.
        ingresos_por_producto[producto] += importe
    else:                                 # Si es la primera vez que aparece ese producto, se crea la clave y se le asigna el importe inicial.
        ingresos_por_producto[producto] = importe

# ----Paso 2: Convertir a DataFrame para filtrar y ordenar----

tabla_ingresos = pd.DataFrame( # convierto el diccionario a una lista de tuplas (producto, total) para poder transformarlo fácilmente en un DataFrame de Pandas.
    [(prod, total) for prod, total in ingresos_por_producto.items()],
    columns=['producto', 'ingresos_totales']
)

# Se ordena de mayor a menor
tabla_ingresos = tabla_ingresos.sort_values(by='ingresos_totales', ascending=False) #los productos con mayores ventas aparecen primero.

# ----Paso 3: Filtrar productos de alto rendimiento----

# Considero "alto rendimiento" los que tienen ingresos > promedio
promedio_ingresos = tabla_ingresos['ingresos_totales'].mean() #Calculo el promedio general de ingresos (mean()).
tabla_alto_rendimiento = tabla_ingresos[tabla_ingresos['ingresos_totales'] > promedio_ingresos]


# ----Paso 4: Mostrar resultados----

print("---- Productos de alto rendimiento ----")
display(tabla_alto_rendimiento)

# ----Paso 1: Agrupar y resumir por categoría----

resumen_cat = (
    ventas.groupby('categoria', as_index=False)
          .agg(
              ingresos=('importe', 'sum'),        # se suma dinero por categoría
              unidades=('cantidad', 'sum'),       # se suma unidades vendidas
              transacciones=('id_venta', 'count') # cantidad de ventas
          )
          .sort_values('ingresos', ascending=False) # orden de mayor a menor ingresos
)

# ----Paso 2: Calcular participación % sobre el total----

total_ingresos = resumen_cat['ingresos'].sum() # calculo la suma total de ingresos
resumen_cat['participacion_%'] = (resumen_cat['ingresos'] / total_ingresos * 100).round(2) # porcentaje que representa cada categoria y con el .round(2) lo redondea a dos digitos

# ----Paso 3: Calcular ticket promedio por transacción----

resumen_cat['ticket_promedio'] = (resumen_cat['ingresos'] / resumen_cat['transacciones']).round(2)

# ----Paso 4: Mostrar resultado----

print("---- Resumen de ventas por categoría ----")
display(resumen_cat)

# Paso previo: Revisar si estan las columnas
print("Columnas en ventas:", ventas.columns.tolist())
print("Columnas en marketing:", marketing.columns.tolist())

# ----Paso 1: Merge usando la columna 'producto' como clave----

ventas_marketing = pd.merge( # combino dos DataFrames basándose en una columna clave
    ventas,
    marketing,
    on='producto',         # esta columna esta en ambos dataset
    how='left',            # mantengo todas las filas de ventas
    suffixes=('_venta', '_marketing') # Sirve para evitar confusiones cuando hay columnas con el mismo nombre en ambos DataFrames.
)

# ----Paso 2: Revisar resultado----

print("\n ---- Vista rápida del dataset combinado ----")
print("\n Shape combinado:", ventas_marketing.shape)
display(ventas_marketing.head(5))

"""# Etapa 3: Actividad 1
**Estadística Descriptiva:** Calcular medidas de tendencia central y dispersión
sobre las ventas. Presentar los resultados en un informe.
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ----Estadísticas descriptivas----

cols_num = [c for c in ['importe','precio','cantidad'] if c in ventas.columns]

if not cols_num:
    print("No se encontraron columnas numéricas objetivo en ventas.") # aunque esto ya fue verificado en la pre-entrega
else:
    # Estadísticas descriptivas con describe()
    descripcion = ventas[cols_num].describe(percentiles=[0.01,0.05,0.25,0.5,0.75,0.95,0.99]).T # Uso describe() para obtener medidas estándar (count, mean, std, percentiles).

    # Añado percentiles extremos (1%, 5%, 95%, 99%) para detectar outliers

    # Agrego rango (max - min)
    descripcion['rango'] = descripcion['max'] - descripcion['min'] # añado el rango para tener el cuenta la disperción

    print("---- Estadísticas descriptivas (importe / precio / cantidad) ----")
    display(descripcion)

    # Cálculos adicionales que podrian ser útiles
    totales = {
        'ventas_totales': ventas['importe'].sum() if 'importe' in ventas.columns else np.nan,
        'total_transacciones': ventas.shape[0],
        'precio_promedio': descripcion.loc['precio','mean'] if 'precio' in descripcion.index else np.nan,
        'cantidad_promedio': descripcion.loc['cantidad','mean'] if 'cantidad' in descripcion.index else np.nan,
        'ticket_promedio_global': (ventas['importe'].sum() / ventas.shape[0]) if ventas.shape[0] > 0 else np.nan
    }

    print("\n---- Tabla resumen rápida de indicadores clave ----")
    resumen_indicadores = pd.DataFrame(list(totales.items()), columns=['metrica','valor'])
    display(resumen_indicadores)

#----Ingresos por producto y productos de alto rendimiento----

# Aseguro que las columnas necesarias existan, aunque ya lo hice en la pre entrega
if ('producto' not in ventas.columns) or ('importe' not in ventas.columns):
    print("No existe columna 'producto' o 'importe' para calcular ingresos por producto.")
else:
    ingresos_producto = ventas.groupby('producto', as_index=False).agg(
        ingresos_totales = ('importe','sum'),
        unidades_vendidas = ('cantidad','sum'),
        transacciones = ('importe','count'),
        precio_promedio = ('precio','mean')
    ).sort_values('ingresos_totales', ascending=False)

    # Calculo percentil 75, para usar como alto rendimiento
    p75 = ingresos_producto['ingresos_totales'].quantile(0.75)
    ingresos_producto['alto_rendimiento'] = ingresos_producto['ingresos_totales'] >= p75

    print("---- Top 10 productos por ingresos totales ----")
    display(ingresos_producto.head(10))

    print(f"\nPercentil 75 (umbral alto rendimiento): {p75:,.2f}") # redondeo a dos dìgitos

    print("\n---- Productos de alto rendimiento (>= p75) ----")
    tabla_alto = ingresos_producto[ingresos_producto['alto_rendimiento']].copy() #creo nuevo df con alto rendimiento
    # tabla alto rendimiento resumen para documentar
    tabla_alto_resumen = tabla_alto[['producto','ingresos_totales','unidades_vendidas','transacciones','precio_promedio']].reset_index(drop=True)
    display(tabla_alto_resumen)

    # Guardo en variables para usar luego
    ingresos_por_producto = ingresos_producto
    productos_alto = tabla_alto_resumen

# -------------------------------
# Verificaciones visuales finales
# -------------------------------


print("\nConteo de filas por producto (top 10):")
if 'producto' in ventas.columns:
    display(ventas['producto'].value_counts().head(10)) # ayuda a detectar productos con mucha frecuencia que pueden sesgar resultados.


# Comprobación: cuántos productos forman el top alto_rendimiento
if 'ingresos_totales' in ingresos_por_producto.columns:
    total_productos = ingresos_por_producto.shape[0]
    num_alto = ingresos_por_producto['alto_rendimiento'].sum()
    print(f"\nTotal productos: {total_productos}  |  Productos alto rendimiento: {num_alto} (top {num_alto/total_productos:.2%})")

"""# Justificación Actividad 3.1
Calculé medidas de tendencia central (media, mediana), dispersión (desviación estándar, rango) y percentiles relevantes (1%, 5%, 25%, 50%, 75%, 95%, 99%) para importe, precio y cantidad. Además, consolidamos indicadores de negocio (ventas totales, ticket promedio global) y generé una tabla de productos de alto rendimiento usando el percentil 75 como umbral, presentando una tabla resumen con ingresos, unidades vendidas, transacciones y precio promedio.

# Etapa 3: Actividad 2

Análisis Exploratorio de Datos (EDA): Realizar un análisis
exploratorio utilizando visualizaciones para identificar patrones y tendencias
en las ventas.
"""

# ----Histograma de importe----
# utilizo matplotlib para mejor visualización

plt.figure(figsize=(10,5))
plt.hist(ventas["importe"].dropna(), bins=40, edgecolor="black") # los bins son la cantidad de barras
plt.title("Distribución de Importe por Transacción")
plt.xlabel("Importe")
plt.ylabel("Frecuencia")
plt.grid(axis="y", alpha=0.3)
plt.show()

"""*Interpretación del gráfico:*

El histograma de importes muestra una distribución claramente sesgada hacia la derecha, con una gran concentración de transacciones en valores bajos y medianos. La mayor parte de los importes se ubica entre los 50 y los 500 pesos, donde se observan las barras más altas. A partir de los 500 pesos, la frecuencia comienza a disminuir de manera progresiva, lo que sugiere que las ventas de importes más altos son menos comunes pero siguen presentes de manera constante.
"""

#  ----Gráfico Boxplot de importe----
# utilizo matplotlib para mejor visualización

plt.figure(figsize=(6,8))
plt.boxplot(ventas["importe"].dropna(), vert=True)
plt.title("Boxplot de Importe (Detección de Outliers)")
plt.ylabel("Importe")
plt.grid(alpha=0.4) # transparecia de las rayitas de grid
plt.show()

"""*Interpretación del gráfico:*

El boxplot de importes muestra una distribución con una variabilidad marcada y una amplia dispersión entre las ventas. La mediana se ubica alrededor de los 400 pesos, lo que indica que la mitad de las transacciones se concentran por debajo de ese valor, aunque el rango intercuartílico es grande, ya que los valores entre el primer y tercer cuartil varían aproximadamente entre 220 y 710 pesos. Esto sugiere que el negocio maneja distintos niveles de importes, probablemente asociados a diferentes tipos de productos o comportamientos de compra. Además, el gráfico revela una cantidad considerable de outliers en el extremo superior, con importes que superan los 1400–1500 pesos. Estos valores atípicos pueden corresponder a ventas excepcionales, transacciones de clientes específicos o bien posibles errores de carga que sería necesario revisar para garantizar la calidad del análisis. Por otro lado, se observan importes mínimos muy bajos lo que refuerza la idea de que existe una gran heterogeneidad en el valor de las ventas. En conjunto, el boxplot sugiere una estructura de datos con alta dispersión, presencia significativa de valores extremos y un comportamiento muy variado en los importes, aspectos clave a tener en cuenta en el análisis exploratorio y en la toma de decisiones posteriores.
"""

# ----Barras de ingresos por categoría----
# utilizo matplotlib para mejor visualización

if 'categoria' in ventas.columns: # verifico que haya columna categoria en el df
    ingresos_cat = ventas.groupby("categoria")["importe"].sum().sort_values(ascending=False) # agrupa los datos por la columna "categoria", selecciona la columna importe para calcular
                                                                                            # suma los importes por categoría y ordena los valores de menos a mayor

    plt.figure(figsize=(10,6))
    plt.bar(ingresos_cat.index, ingresos_cat.values, color="skyblue")
    plt.title("Ingresos Totales por Categoría")
    plt.xlabel("Categoría")
    plt.ylabel("Ingresres Totales")
    plt.xticks(rotation=45)
    plt.grid(axis="y", alpha=0.3)
    plt.show()

    print("\nTabla de ingresos por categoría:")
    display(ingresos_cat.to_frame("ingresos"))
else:
    print("No existe la columna 'categoria' en el dataset.") # en caso de que la columna categoria no este en el df

"""*Interpretación del gráfico:*


El gráfico de barras que representa los ingresos totales por categoría muestra que las tres categorías —Electrodomésticos, Electrónica y Decoración— generan volúmenes de ingresos muy similares, aunque con ligeras diferencias que permiten identificar cuál aporta más al total. Electrodomésticos aparece como la categoría líder, con ingresos que superan los 500.000 pesos, posicionándose como el segmento más rentable dentro del conjunto de datos. Le sigue Electrónica, que presenta un nivel de ingresos apenas inferior pero igualmente alto, lo que sugiere que es una categoría con fuerte demanda y un comportamiento comercial estable. Finalmente, Decoración se ubica muy cerca de Electrónica, también con un volumen elevado de ingresos, indicando que, aunque ligeramente por debajo, contribuye de manera significativa al total general.

"""

# ----TOP 10 productos----
# utilizo matplotlib para mejor visualización

top_prod = (
    ventas.groupby("producto")["importe"] #agrupo el DataFrame ventas por la columna "producto" y luego selecciona la columna "importe" para realizar los cálculos necesarios.
          .sum()
          .sort_values(ascending=False) # ordeno en forma descendente
          .head(10) # asi selecciono los primeros 10
)

plt.figure(figsize=(15,6))
plt.bar(top_prod.index, top_prod.values, color="skyblue")
plt.title("Top 10 Productos por Ingresos")
plt.xlabel("Producto")
plt.ylabel("Ingresos Totales")
plt.xticks(rotation=45)
plt.show()

print("\nTabla top 10 productos:")
display(top_prod.to_frame("ingresos"))

# ----Ventas mensuales----


if "fecha_venta" in ventas.columns: # verifico que exista la columna fechas
    ventas["año_mes"] = ventas["fecha_venta"].dt.to_period("M") # creo columna de fecha con formato año-mes

    ventas_mensuales = ventas.groupby("año_mes")["importe"].sum() # agrupo por la columna año_mes recién creada y calcula la suma del importe para cada grupo

    plt.figure(figsize=(12,5))
    plt.plot(ventas_mensuales.index.astype(str),
             ventas_mensuales.values,
             marker="o")
    plt.title("Evolución de Ventas Mensuales")
    plt.xlabel("Año-Mes")
    plt.ylabel("Ingresos Totales")
    plt.xticks(rotation=45)
    plt.grid(alpha=0.3)
    plt.show()

    print("\nTabla de ventas mensuales:")
    display(ventas_mensuales.to_frame("ingresos"))
else:
    print("No existe la columna fecha_venta para analizar ventas mensuales.")

"""*Interpretación del gráfico:*

Durante el primer trimestre, las ventas se mantienen relativamente altas, destacándose enero y especialmente marzo, donde los ingresos superan los 136.000 pesos. En mayo se observa el punto máximo del año, con un pico cercano a los 144.000 pesos, lo que sugiere un mes de fuerte actividad comercial, posiblemente por promociones, lanzamientos o mayor demanda propia del período. Sin embargo, a partir de ese punto se registra una caída abrupta en junio, que se convierte en el valor mínimo de todo el año, rondando los 108.000 pesos. Tras esta baja, los meses siguientes muestran una recuperación gradual, aunque sin alcanzar nuevamente los niveles del primer semestre: julio y agosto evidencian una mejora moderada, mientras que septiembre y octubre vuelven a descender levemente. Finalmente, noviembre presenta un repunte que devuelve las ventas a un nivel similar al de agosto, antes de cerrar diciembre con una ligera caída. En conjunto, la serie temporal refleja una fuerte estacionalidad, con un primer semestre más sólido y un segundo semestre estable pero con menor intensidad, información clave para planificar estrategias comerciales y operativas.
"""

# ----Selección de columnas numéricas----

# Selecciono columnas que son numéricas
num_cols = ventas.select_dtypes(include='number')

print("Columnas numéricas detectadas:")
display(num_cols.head())

"""# Etapa 3: Actividad 3

Correlación: Evaluar la relación entre diferentes variables (por ejemplo,
precio y cantidad vendida) y mostrar los resultados en un gráfico.
"""

# ----Matriz de correlación----


corr_matrix = num_cols.corr(method='pearson') # utilizo .corr(method='pearson') para medir la relacion lineal entre las variables
# los valores deben fluctuar entre -1 y 1

# 1.0 → correlación positiva perfecta
#0.0 → no correlación
#-1.0 → correlación negativa perfecta

print("---- Matriz de correlación ----")
display(corr_matrix)

# Mapa de calor de correlación


plt.figure(figsize=(10,6))
sns.heatmap(
    corr_matrix,
    annot=True,        # muestra el valor numérico en cada celda
    cmap="coolwarm",   # colores intuitivos: azul (-), rojo (+)
    fmt=".2f", #redondeo de dos dígitos
    linewidths=0.5
)
plt.title("Mapa de Calor de Correlación entre Variables Numéricas")
plt.show()

"""*Interpretación del mapa de calor:*

Una matriz de correlación es una tabla que muestra qué tan relacionadas están las variables numéricas entre sí, usando valores entre -1 y 1, donde 1 significa que suben juntas perfectamente, -1 que cuando una sube la otra baja, y 0 que no tienen relación. En este heatmap de ventas, lo más relevante es que el importe total está fuertemente relacionado con la cantidad vendida (0.77, color naranja-rojizo) y moderadamente con el precio (0.56, color beige-naranja), lo que indica que en el negocio, vender más unidades impacta más en el total de ventas que vender productos caros. Los colores ayudan a visualizar esto: rojo indica correlación fuerte positiva, azul indica poca o ninguna correlación (como el id_venta que no se relaciona con nada porque es solo un identificador), y los valores en la diagonal son siempre 1.00 porque cada variable se correlaciona perfectamente consigo misma. En resumen, los datos muestran que para aumentar ingresos, la estrategia de vender mayor cantidad de productos es más efectiva que enfocarse solo en precios altos.

*Justificación de la actividad:*

Realicé un análisis de correlación entre las variables numéricas del conjunto de datos con el objetivo de evaluar la relación existente entre ellas.

Como herramienta visual, construí un heatmap mediante la librería Seaborn. Esta visualización permite identificar de forma rápida y clara qué variables presentan correlaciones positivas, negativas o nulas, mediante una escala de colores y la inclusión de los valores numéricos dentro de cada celda. Este enfoque facilita la detección de patrones globales, posibles dependencias y relaciones relevantes para el análisis de ventas.

# Etapa 3: Actividad 4

Consolidación de Datos: Consolidar todos los análisis previos y preparar un
conjunto de datos final que resuma los hallazgos clave para la presentación.
"""

# Consolidación por producto

tabla_producto = (
    ventas.groupby("producto")
          .agg( # agrupo el df ventas por producto
              precio_promedio=("precio", "mean"), # calculo la media de precio
              unidades_totales=("cantidad", "sum"), #media de cantidad
              ingresos_totales=("importe", "sum"), #media ingresos totales
              transacciones=("id_venta", "count")# media transacciones
          )
          .reset_index()
)

# Ticket promedio por producto
tabla_producto["ticket_promedio"] = ( # creo columna de ticket promedio
    tabla_producto["ingresos_totales"] / tabla_producto["transacciones"]
)

# Merge con marketing
if "producto" in marketing.columns: # verifico que producto existe en el df de marketing
    tabla_producto = tabla_producto.merge(
        marketing[["producto", "id_campanha", "canal", "costo"]],
        on="producto",
        how="left"
    ) # hago merge entre los df usando como key la columna producto

display(tabla_producto.head())

# ----Consolidación por categoría----


tabla_categoria = (
    ventas.groupby("categoria", as_index=False) # agrupo el df ventas por categoria
          .agg(
              ingresos=("importe", "sum"), # sumo ingresos
              unidades=("cantidad", "sum"), # sumo unidades
              transacciones=("id_venta", "count") # número de transacciones
          )
)

# Porcentaje de participación
total_ingresos = tabla_categoria["ingresos"].sum() # Calculo el total de ingresos sumando la columna "ingresos" de la tabla recién creada.
tabla_categoria["participacion_%"] = (
    tabla_categoria["ingresos"] / total_ingresos * 100 # se añade una nueva columna "participacion_%" que calcula el porcentaje de ingresos de cada categoría respecto al total
).round(2) # redondeo a dos dígitos

# Ticket promedio
tabla_categoria["ticket_promedio"] = (
    tabla_categoria["ingresos"] / tabla_categoria["transacciones"] #Añado una columna "ticket_promedio" que es el resultado de dividir los ingresos por el número de transacciones
)

display(tabla_categoria)

# ----Consolidación mensual----


if "fecha_venta" in ventas.columns: # me aseguro que exista la columna en el df
    ventas["año_mes"] = ventas["fecha_venta"].dt.to_period("M") # ordeno las fechas como año-mes

    tabla_mensual = (
        ventas.groupby("año_mes")["importe"] # agrupa los datos por la columna "año_mes" y selecciona la columna "importe".
              .sum() # lo suma
              .reset_index()
    )

    display(tabla_mensual)
else:
    print("No existe fecha_venta para consolidar ventas temporales.")

# ----Golden Dataset final----


golden = ventas.copy() # hago copia del df original ventas

# Selección de columnas clave
golden = golden[[ # selecciono las columnas de interés
    "id_venta", "producto", "categoria", "precio", "cantidad",
    "importe", "fecha_venta"
]]

# Ranking por ingresos
ranking = (
    golden.groupby("producto")["importe"] #agrupo por "producto" y se suma el "importe" para poder obtener los ingresos totales por producto
          .sum()
          .sort_values(ascending=False) # de manera descendente
          .reset_index()
)
ranking["ranking_ingresos"] = ranking["importe"].rank(ascending=False) # creo nueva columna ranking_ingresos donde se asigna un rango a cada producto basado en sus ingresos totales de manera descendente

# Merge para agregar el ranking
golden = golden.merge(ranking[["producto", "ranking_ingresos"]], # hago merge entre el dataset golden y el ranking (solo con las columnas "producto" y "ranking_ingresos") usando la columna "producto" como key
                      on="producto",
                      how="left")

display(golden.head())

# ----Verificaciones----


print("=== Shape de cada tabla ===")
print("Producto:", tabla_producto.shape)
print("Categoría:", tabla_categoria.shape)
print("Mensual:", tabla_mensual.shape)
print("Golden:", golden.shape)

print("\nTipos de datos:")
display(golden.dtypes.to_frame("dtype"))

"""# Justificación Etapa 3: Actividad 4
Para esta actividad consolidé todos los análisis previos en diferentes tablas resumen.
Generé una tabla por producto que incluye métricas clave como ingresos totales, unidades vendidas, ticket promedio, transacciones y precio promedio. Adicionalmente, realicé una integración con el dataset de marketing para incorporar información contextual de las campañas.

Luego, construí una tabla por categoría que resume el rendimiento general y calculé la participación porcentual de cada categoría en los ingresos totales. También generé una vista temporal de las ventas agregadas por mes, lo que permite evaluar tendencias y estacionalidad.

Finalmente, elaboré un “Golden Dataset” que reúne las variables más relevantes de ventas e incorpora un ranking de productos según ingresos. Este dataset final será utilizado para las visualizaciones y la presentación del informe, cumpliendo con el objetivo de tener un conjunto de datos limpio, unificado y orientado al análisis.

#*Etapa 4*: Actividad 1

Visualización con Matplotlib: Crear gráficos básicos (líneas, barras,
dispersión) que representen las ventas con diferentes periodos de tiempo.
"""

# ----Preparación de fechas----


# Me aseguro que columna de fechas convertida a datetime, aunque en la pre-entrega ya lo realice
ventas["fecha_venta"] = pd.to_datetime(ventas["fecha_venta"], errors="coerce")

# Creo columnas temporales que me pueden ser útiles
ventas["año"] = ventas["fecha_venta"].dt.year
ventas["mes"] = ventas["fecha_venta"].dt.month
ventas["año_mes"] = ventas["fecha_venta"].dt.to_period("M")
ventas["dia"] = ventas["fecha_venta"].dt.day

# ----GRÁFICO DE LÍNEAS: Ventas mensuales----


ventas_mensuales = ventas.groupby("año_mes")["importe"].sum() # Agrupo el df ventas por la columna "año_mes" y calcula la suma de la columna "importe" para cada grupo

plt.figure(figsize=(12,6))
plt.plot(
    ventas_mensuales.index.astype(str),
    ventas_mensuales.values,
    marker="o",
    linewidth=2
)

plt.title("Ventas Mensuales - Línea de Tendencia")
plt.xlabel("Año-Mes")
plt.ylabel("Ingresos Totales")
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.show()

print("Tabla de ventas mensuales:")
display(ventas_mensuales.to_frame("ingresos")) # visualizo claramente en una tabla las ventas mensuales con sus ingresos

"""*Interpretación del gráfico de líneas:*

El gráfico refleja con claridad la dinámica del año y permite visualizar de manera más directa los cambios abruptos y los momentos de mayor rendimiento. Durante el primer semestre, la tendencia muestra un comportamiento ascendente hasta alcanzar su punto máximo en mayo, mes en el que las ventas se elevan a alrededor de 144.000 pesos, consolidándose como el pico anual. Sin embargo, inmediatamente después se observa una caída muy marcada en junio, donde los ingresos descienden a su nivel más bajo del período analizado. A partir de ese punto crítico, la tendencia comienza a recuperarse gradualmente durante los meses siguientes, aunque sin volver a alcanzar los valores del primer semestre. Entre julio y noviembre se percibe una estabilización en torno a los 115.000–120.000 pesos, con pequeñas subidas y bajadas que forman un patrón de oscilación leve. Finalmente, diciembre cierra el año con un valor ligeramente inferior al de noviembre, manteniendo la línea descendente suave del último tramo. En conjunto, la tendencia evidencia un ciclo anual en el que el primer semestre es más fuerte y presenta mayor variabilidad, mientras que el segundo semestre muestra estabilidad pero con niveles más bajos, aportando información clave para interpretar la estacionalidad y planificar futuras estrategias comerciales.
"""

# ----BARRAS: Ventas por mes----


ventas_mes_cal = ventas.groupby("mes")["importe"].sum() # agrupo el df ventas por la columna "mes" y calcula la suma de la columna "importe" para cada grupo

plt.figure(figsize=(10,6))
plt.bar(ventas_mes_cal.index, ventas_mes_cal.values, color="orange")
plt.title("Ventas Totales por Mes (Independiente del Año)")
plt.xlabel("Mes")
plt.ylabel("Ingresos Totales")
plt.xticks(range(1,13))
plt.grid(axis="y", alpha=0.3)
plt.show()

display(ventas_mes_cal.to_frame("ingresos"))

"""*Interpretación del gráfico de barras:*

El gráfico de ventas totales por mes, del año 2024, revela un patrón estacional bastante marcado que ayuda a identificar cuáles son los períodos de mayor actividad comercial. Los valores más altos se concentran entre marzo y mayo, destacándose mayo como el mes con mayores ingresos, superando los 140.000 pesos. Este pico sugiere que durante el segundo trimestre se da una combinación de factores favorables: mayor demanda, campañas promocionales o ciclos naturales del negocio que impulsan las compras. Enero y abril también muestran cifras elevadas, lo que refuerza la idea de que el primer cuatrimestre del año suele ser más fuerte en términos de ventas. En contraste, los meses de junio y octubre registran los valores más bajos, situándose alrededor de los 110.000–113.000 pesos, lo que indica una disminución del consumo en esos períodos. El resto del año presenta un comportamiento más estable, con variaciones pequeñas entre un mes y otro, manteniéndose en torno a los 115.000–120.000 pesos. En conjunto, la distribución mensual evidencia una estacionalidad clara: un inicio de año fuerte, un pico destacado en mayo y una leve desaceleración durante el segundo semestre. Este análisis permite anticipar períodos críticos y planificar estrategias comerciales adaptadas a los ciclos del negocio.
"""

# ----DISPERSIÓN: Importe vendido por día del mes----


plt.figure(figsize=(10,6))
plt.scatter(
    ventas["dia"], # valor de dia para el eje x
    ventas["importe"], # valor de importe para eje y
    alpha=0.5
)

plt.title("Relación entre Día del Mes e Importe Vendido")
plt.xlabel("Día del Mes")
plt.ylabel("Importe de la Venta")
plt.grid(alpha=0.3)
plt.show()

"""*Interpretación del gráfico de disperción (scatter):*

El diagrama de dispersión que relaciona el día del mes con el importe vendido muestra que no existe un patrón lineal claro entre ambas variables: las ventas se distribuyen de manera bastante uniforme a lo largo de los 31 días. Sin embargo, se observa una concentración más densa de transacciones en importes bajos y medios —entre 100 y 700 pesos— mientras que los valores altos, por encima de 1.200 pesos, aparecen con menor frecuencia pero repartidos en casi todos los días del mes. Esto sugiere que las ventas de mayor importe no dependen de fechas específicas, sino que ocurren de manera aleatoria. También se percibe una ligera mayor densidad de puntos en los primeros diez días y hacia fin de mes, lo que podría relacionarse con ciclos salariales o comportamientos comunes de consumo, aunque no es una tendencia fuerte. En conjunto, los datos reflejan un flujo de ventas continuo y estable durante todo el mes, sin días “críticos” ni picos concentrados, lo que indica un comportamiento de compra distribuido y sin estacionalidad diaria marcada.
"""

# ----Verificación adicional----


print("\nPrimeras filas del dataset temporal:")
display(ventas[["fecha_venta", "año_mes", "importe"]].head(10))

"""# Etapa 4: Actividad 2

Visualización Avanzada con Seaborn: Desarrollar visualizaciones
estadísticas avanzadas, utilizando paletas y estilos para mejorar la
presentación.
"""

# ----Top 10 productos----


top10 = ventas["producto"].value_counts().head(10).index # cuanta la frecuencia de cada producto, los 10 mas frecuentes
subset = ventas[ventas["producto"].isin(top10)] # filtra el df ventas para quedarse solo con las filas donde el producto está en la lista top10

plt.figure(figsize=(12,6))
sns.countplot(
    data=subset,
    y="producto",
    order=top10,
    hue="producto",       # evito el warning al especificar que variable estoy "coloreando"
    palette="Set3",
    legend=False          # para que no se repita la leyenda
)
plt.title("Top 10 Productos por Cantidad de Transacciones")
plt.xlabel("Transacciones")
plt.ylabel("Producto")
plt.show()

"""*Interpretación del gráfico:*

El gráfico de barras revela claramente cuáles son los productos más vendidos según la cantidad de transacciones. La Lámpara de mesa destaca ampliamente como el artículo con mayor movimiento, superando con comodidad al resto y posicionándose como el preferido de los clientes. Le siguen los Auriculares y los Microondas, ambos con un volumen de ventas alto y bastante parejo, lo que indica una demanda sostenida en categorías tanto de tecnología como de hogar. En un nivel intermedio aparece la Cafetera, que también muestra un desempeño sólido. El resto de los productos —Smartphone, Rincón de plantas, Adorno de pared, Aspiradora, Cortinas y Freidora eléctrica— mantienen un nivel similar de transacciones, lo que sugiere una rotación estable pero menos dominante dentro del top 10. En conjunto, el gráfico deja ver una combinación equilibrada entre artículos decorativos, electrodomésticos y tecnología, aunque con una clara inclinación de los consumidores por productos prácticos y de uso cotidiano.
"""

# ----CATPLOT: Ingresos por mes----


mensual = ventas.groupby("mes")["importe"].sum().reset_index() # agrupa por la columna 'mes' y selecciona 'importe'.
                                                              # suma total de ingresos para cada mes y quita el índice
sns.catplot(
    data=mensual,
    x="mes",
    y="importe",
    kind="bar",
    palette="mako",
    height=5,
    aspect=1.5,
    hue="mes", # lo mismo que en el anterior, evito el warning al especificar que variable estoy "coloreando"
    legend=False # evito que se repita la leyenda
)

plt.title("Ingresos por Mes (Catplot Avanzado)")
plt.xlabel("Mes")
plt.ylabel("Ingresos")
plt.show()

"""*Interpretación del gráfico:*

El gráfico muestra los ingresos mensuales con un patrón que ya vimos antes: picos fuertes en los primeros meses del año —especialmente en marzo y mayo— y una caída marcada en junio. A partir de ahí, los valores se estabilizan alrededor de un rango similar durante el resto del año, con leves subidas en noviembre y diciembre. Aunque el estilo visual cambia, la tendencia general se mantiene: buen arranque, un bajón a mitad de año y luego estabilidad.
"""

# BOXLOT por categoría


plt.figure(figsize=(12,6))
sns.boxplot(
    data=ventas,
    x="categoria",
    y="importe",
    palette="Set2",
    hue="categoria", # lo mismo que en el anterior, evito el warning al especificar que variable estoy "coloreando"
    legend=False # evito que se repita la leyenda
)
plt.title("Distribución del Importe por Categoría")
plt.xlabel("Categoría")
plt.ylabel("Importe")
plt.xticks(rotation=45)
plt.show()

"""*Interpretación del gráfico:*

El gráfico de caja muestra la distribución del importe de ventas para tres categorías de productos: Decoración, Electrodomésticos y Electrónica. Al analizar los datos, se observa que las tres categorías presentan comportamientos relativamente similares en términos de dispersión y tendencia central. La mediana del importe para Decoración se encuentra alrededor de los  400 pesos, mientras que Electrodomésticos y Electrónica muestran medianas ligeramente superiores, cerca de los 400-450 pesos. En cuanto a la dispersión, todas las categorías presentan rangos intercuartílicos (representados por las cajas) bastante variados, lo que indica variabilidad en los importes. Hay algunos valores atípicos (outliers) en las categorias de electrónica y electrodomésticos. Estos outliers sugieren que, aunque la mayoría de las transacciones se concentran en rangos medios-bajos, ocasionalmente se registran ventas de importe considerablemente más elevado. En general, el gráfico evidencia que no existen diferencias sustanciales entre las categorías en términos de comportamiento de importes, manteniendo todas un patrón similar de distribución.
"""

# ---- Gráfico de Dispeción----

plt.figure(figsize=(9,6))
sns.scatterplot(
    data=ventas,
    x="precio",
    y="cantidad",
    alpha=0.5,
    palette="muted",
    hue="categoria"  # Colorea por categoría
)
plt.title("Dispersión: Precio vs Cantidad")
plt.xlabel("Precio")
plt.ylabel("Cantidad")
plt.grid(alpha=0.3)
plt.legend(title='Categoría', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""*Interpretación del gráfico:*

El gráfico de dispersión, que compara el Precio con la Cantidad (unidades vendidas) de artículos, revela falta de correlación entre estas dos variables dentro del conjunto de datos. Se observa que la variable Precio se distribuye de manera uniforme a lo largo del eje x. Por otro lado, la variable Cantidad es discreta, con puntos solo presentes en valores enteros del 1 al 12 en el eje y. La distribución horizontal de los puntos en cada nivel de Cantidad indica que artículos de alta cantidad (cercanos a 12) y de baja cantidad (cercanos a 1)se venden en todo el espectro de precios. Además, al segmentar los datos por las categorías **Decoración**, **Electrodomésticos** y **Electrónica**, se aprecia una superposición casi total. Esto significa que las tres categorías de producto tienen un comportamiento de precios y cantidades vendidas que es homogéneo, sin que ninguna de ellas se concentre de manera significativa en niveles de precio o cantidad distintos a las otras. En resumen, ni el precio ni la categoría del producto parecen ser factores determinantes para el volumen de la Cantidad en este conjunto de datos.
"""

# ----Gráfico de Barras----
ingresos_cat = ventas.groupby("categoria")["importe"].sum().sort_values()

plt.figure(figsize=(10,6))
sns.barplot(
    x=ingresos_cat.values,
    y=ingresos_cat.index,
    palette="mako",
    hue=ingresos_cat.index,


)

plt.xlim(400000, None)   # Arranco el eje X en 400k, para que se pueda ver mejor la diferencia de las barras entre las categorias
plt.title("Ingresos Totales por Categoría")
plt.xlabel("Ingresos")
plt.ylabel("Categoría")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""*Interpretación del gráfico:*

El análisis de los Ingresos Totales por Categoría revela una clara jerarquía en la contribución financiera de los productos. La categoría de Electrodomésticos se posiciona como el principal motor de ingresos. Le siguen las categorías de Electrónica y Decoración, las cuales presentan niveles de ingresos muy competitivos y cercanos entre sí. Si bien Electrónica ocupa formalmente el segundo lugar y Decoración el tercero, la diferencia monetaria entre ambas es mínima. En resumen, Electrodomésticos establece el liderazgo en la generación de valor monetario, siendo crucial para el rendimiento económico general, mientras que Electrónica y Decoración demuestran una contribución significativa y equilibrada al total de ingresos.
"""

# ----Gráfico de Línea----
from matplotlib import lines
ventas_mensuales = ventas.groupby("año_mes")["importe"].sum().reset_index() # agrupo por la columna año_mes y calcula la suma del importe para cada grupo

plt.figure(figsize=(12,5))
sns.lineplot(
    data=ventas_mensuales,
    x=ventas_mensuales["año_mes"].astype(str), # Convert 'año_mes' to string for plotting
    y="importe",
    marker="o",
    linewidth=2,
    color="blue",
    linestyle="--"
)
plt.title("Tendencia de Ventas Mensuales")
plt.xlabel("Año-Mes")
plt.ylabel("Ingresos Totales")
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.show()

"""*Interpretación del gráfico de líneas:*

El gráfico con la línea de tendencia de las ventas mensuales refleja con claridad la dinámica del año y permite visualizar de manera más directa los cambios abruptos y los momentos de mayor rendimiento. Durante el primer semestre, la tendencia muestra un comportamiento ascendente hasta alcanzar su punto máximo en mayo, mes en el que las ventas se elevan a alrededor de 144.000 pesos, consolidándose como el pico anual. Sin embargo, inmediatamente después se observa una caída muy marcada en junio, donde los ingresos descienden a su nivel más bajo del período analizado. A partir de ese punto crítico, la tendencia comienza a recuperarse gradualmente durante los meses siguientes, aunque sin volver a alcanzar los valores del primer semestre. Entre julio y noviembre se percibe una estabilización en torno a los 115.000–120.000 pesos, con pequeñas subidas y bajadas que forman un patrón de oscilación leve. Finalmente, diciembre cierra el año con un valor ligeramente inferior al de noviembre, manteniendo la línea descendente suave del último tramo. En conjunto, la tendencia evidencia un ciclo anual en el que el primer semestre es más fuerte y presenta mayor variabilidad, mientras que el segundo semestre muestra estabilidad pero con niveles más bajos, aportando información clave para interpretar la estacionalidad y planificar futuras estrategias comerciales.

# Etapa 4: Actividad 3

Visualización Interactiva con Plotly: Construir un dashboard interactivo
que combine múltiples visualizaciones, permitiendo al usuario explorar los
datos dinámicamente.
"""

# ----Gráfico de líneas (Interactivo)----
import plotly.express as px
ventas_mensuales = ventas.groupby("año_mes")["importe"].sum().reset_index() # agrupo por la columna año_mes y calcula la suma del importe para cada grupo

ventas_mensuales["año_mes_str"] = ventas_mensuales["año_mes"].astype(str) # para que quede bien en el gráfico es más sencillo pasarlo a str

fig1 = px.line(
    ventas_mensuales,
    x="año_mes_str", # Use the string version año_mes
    y="importe",
    markers=True,
    title="Evolución Mensual de Ventas (Interactiva)"
)

fig1.update_layout(
    xaxis_title="Año-Mes",
    yaxis_title="Ingresos Totales",
    template="plotly_white"
)

fig1.show()

# ----Gráfico de Barras (Interactivo)----
ing_cat = ventas.groupby("categoria")["importe"].sum().reset_index() # agrupo por la columna categoria y calcula la suma del importe para cada grupo

fig2 = px.bar(
    ing_cat,
    x="categoria",
    y="importe",
    title="Ingresos Totales por Categoría",
    text_auto=True,
    color="categoria"
)

# Arranco el eje Y en 400k, para que se pueda ver mejor la diferencia de las barras entre las categorias
fig2.update_yaxes(range=[400000, None])

fig2.update_layout(
    xaxis_title="Categoría",
    yaxis_title="Ingresos",
    template="plotly_white",
    showlegend=False
)

fig2.show()

# ----Gráfico Scatter (Interactivo)----
fig3 = px.scatter(
    ventas,
    x="precio",
    y="cantidad",
    color="categoria",
    hover_data=["producto", "importe"],
    title="Relación Precio vs Cantidad (Interactivo)",
    opacity=0.6
)

fig3.update_layout(
    xaxis_title="Precio",
    yaxis_title="Cantidad Vendida",
    template="plotly_white"
)

fig3.show()

# ----Sunburst Interactivo: Categoría, Producto----


ventas_agrup = (
    ventas.groupby(["categoria", "producto"])["importe"] # agrupo el df ventas por dos columnas: primero por "categoria" y luego por "producto"
          .sum() # calculo la suma de los importes para cada combinación única de categoría y producto
          .reset_index()
)

fig4 = px.sunburst(
    ventas_agrup,
    path=["categoria", "producto"],  # jerarquía
    values="importe",
    color="categoria",
    title="Distribución Interactiva de Ingresos por Categoría y Producto",
    color_discrete_sequence=px.colors.qualitative.Plotly,
)

fig4.update_layout(template="plotly_white")

fig4.show()

"""El **sunburst** permite visualizar la contribución de cada categoría al total de ingresos, y dentro de cada una, el aporte relativo de cada producto. Gracias a la interactividad de Plotly, el usuario puede navegar jerárquicamente entre categorías y productos con un simple clic, obteniendo el detalle completo sin perder el contexto general.

*Justificación de la actividad:*
Empleé Plotly para generar visualizaciones interactivas que permiten explorar los datos de manera dinámica.
Desarrollé cuatro gráficos principales:

* Línea interactiva de ventas mensuales, útil para analizar tendencias temporales con zoom y tooltip detallado.
* Barras de ingresos por categoría, permitiendo comparar el rendimiento entre categorías de forma clara e intuitiva.
* Scatter interactivo entre precio y cantidad, que facilita la identificación de patrones y diferencias entre categorías mediante interactividad y resaltado individual de productos.
* Sunburst interactivo de ingresos por categoría y producto, ideal para visualizar estructuras jerárquicas y entender cómo se distribuyen los ingresos dentro de cada categoría. Su interactividad permite explorar niveles con clics, manteniendo siempre la proporción visual y facilitando la comparación entre segmentos.

### Un adicional 3D
"""

# Gráfico 3D interactivo con GRAPH_OBJECTS

import plotly.graph_objects as go

fig_3d = go.Figure( # creo la figura del gráfico con configuración 3D
    data=[
        go.Scatter3d(
            x=ventas["precio"],
            y=ventas["cantidad"],
            z=ventas["importe"],
            mode="markers",
            marker=dict( #diccionario que define las propiedades de los marcadores
                size=5, # tamaño marcadores
                color=ventas["importe"],   # se colorea por importe
                colorscale="Viridis",
                opacity=0.7
            ),
            text=ventas["producto"],   # tooltip del producto. el tooltip es la ventana emergente que aparece al pasar el cursor sobre un punto de datos en un gráfico 3D para mostrar información adicional sobre ese punto.
            hovertemplate=(
                # en la ventana donde pasa el cursor aparece en el siguiente orden
                "<b>Producto:</b> %{text}<br>" +
                "Precio: %{x}<br>" +
                "Cantidad: %{y}<br>" +
                "Importe: %{z}<br>"
            )
        )
    ]
)

# Configuración de los ejes y estética
fig_3d.update_layout(
    title="Gráfico 3D Interactivo: Precio, Cantidad e Importe",
    scene=dict(
        xaxis_title="Precio", #eje x
        yaxis_title="Cantidad", #eje y
        zaxis_title="Importe" #eje z (lo que da el 3D)
    ),
    template="plotly_white",
    height=700
)

fig_3d.show()