# -*- coding: utf-8 -*-
"""Melñik Micaela- Comision 252561- Analisis de Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L__J8ZHU0OuG639mzF08__zH6eny-K03

# Pre- entrega
* **Curso:** Data Analytics con Python
* **Comisión:** 25261
* **Alumno:** Micaela del Pilar Melñik
* **Fecha:** 20/10/2025

> **Objetivo:** Explorar, limpiar, transformar e integrar datos de ventas, clientes y marketing para analizar desempeño de productos y efectividad de campañas.
**Etapa 1: Recopilación y Preparación de Datos (Clases 1 a 4)**
**Etapa 2: Preprocesamiento y Limpieza de Datos (Clases 5 a 8)**

*Actividades (des-orden):**

* 1.1. Crear un documento en Google Colaboratory y cargar los sets de datos como DataFrames.
  * *1.4. Introducción a Pandas: realizar un análisis exploratorio inicial de los Dataframes.*
  * *1.5. Calidad de Datos: Identificar valores nulos y duplicados en los conjuntos de datos. Documentar el estado inicial de los datos.*
  * *2.1. Limpieza de Datos: Limpiar el conjunto de datos eliminando duplicados y caracteres no deseados. Documentar el proceso y los resultados.*
* 1.2. Realizar un script básico que calcule las ventas mensuales utilizando variables y operadores.
* 1.3. Estructuras de Datos: Desarrollar un programa que almacene los datos de ventas (producto, precio, cantidad). Decidir si conviene utilizar diccionarios o listas.
* 2.2. Transformación de Datos: Aplicar filtros y transformaciones para crear una tabla de ventas que muestre solo los productos con alto rendimiento.
* 2.3. Agregación: Resumir las ventas por categoría de producto y analizar los ingresos generados.
* 2.4. Integración de Datos: Combinar los sets de datos de ventas y marketing para obtener una visión más amplia de las tendencias.

# Etapa 1: Actividad 1
## Creo un libro de Colab donde cargo los set de datos
"""

# ----IMPORTO PANDAS Y NUMPY----
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

# ----CARGO LOS DATAFRAMES----
ventas    = pd.read_csv("ventas-1.csv")
clientes  = pd.read_csv("clientes-1.csv")
marketing = pd.read_csv("marketing-1.csv")

#----PRIMERA VISTA DE LOS DATAFRAMES----
print("ventas:", ventas.shape)
print("clientes:", clientes.shape)
print("marketing:", marketing.shape)

"""# PRIMER VISTAZO
* Ventas: hay 3035 filas, las transacciones que se registraron, y 6 columnas, las características de la venta.
* Clientes: 567 filas, la cantidad de clientes registrados, y 5 columnas, con las características de estos últimos.
* Marketing: 90 filas, campañas o acciones de marketing, y 6 columnas, los atributos de estas campañas.

# FUERA DE ORDEN
Preferí hacerlo con este orden, ya que tenía los conocimientos para hacer primero la limpieza de datos y luego continuar con el resto del proyecto. Facilité pasos utilizando Pandas desde el principio.
# Etapa 1: Actividad 4 y 5.
## Introducción a Pandas y Calidad de Datos
"""

# Introducción a Pandas y primer análisis exploratorio

def explorar_inicial(df, nombre):
  print()
  print(f"{nombre.upper()} ") # Hago el nombre en forma de título (mayúscula al principio).

  # ----Tamaño y tipo de dato----
  print("Shape (filas, columnas):", df.shape)
  print("\nTipos de datos:")
  print(df.dtypes) # puedo visualizar los titulos de las columnas y los datos que hay en ellas.

  #----Comprobar valores nulos----
  print()
  print("----Nulos por columna ----")
  print(df.isna().sum()) # compruebo los valores nulos en el df y los sumo

  #----Comprobar duplicados----
  print()
  print("----Duplicados----")
  print(df.duplicated().sum()) # busco los duplicados y los sumo

  # ---- Muestra preliminar del contenido ----
  print()
  print("----Primeras 5 filas----")
  display(df.head(5)) # muestro las primeras 5 filas del df

  # ---- Resumen columnas numericas ----
  num = df.select_dtypes(include="number") # filtra las columnas por tipo de dato, en este caso numero. asi que selecciona las columnas numericas.
  if not num.empty: # si es una columna numerica, sigue el bloque de analisis. en caso contratio muestra un mensaje aclarando que no hay columna numerica
    print("Resumen numérico")
    display(num.describe().T) #genera un resumen estadistico de las columnas numericas. el .T hace que las columnas aparezcan como filas, haciendo mas comoda la lectura.
  else:
    print("No hay columnas numéricas")

  # ---- Resumen columnas categóricas ----
  cate = df.select_dtypes(include="object") # filtra las columnas por tipo de dato, en este caso objeto. selecciona las columnas de tipo objeto
  if not cate.empty: # si es una columna de tipo objeto, sigue el bloque de analisis. en caso contrario, muestra un mensaje aclarando que no hay columna de tipo objeto
    print("Resumen categórico")
    display(cate.describe().T) #genera un resumen de las columnas categoricas. el .T hace que las columnas aparezcan como filas, haciendo mas comoda la lectura.
  else:
    print("No hay columnas categóricas")

explorar_inicial(ventas, "ventas")

# ---- Ahora aplico explorar_inicial con Clientes ----
explorar_inicial(clientes, "clientes") # utilizo el primer codigo pero con el df "clientes"

# ---- Ahora aplico explorar_inicial con Marketing ----
explorar_inicial(marketing, "marketing") # utilizo el primer codigo pero con el df marketing

"""# Etapa 2: Actividad 1
## Limpieza de Datos
"""

# ----Control previo----
prev_shape = ventas.shape
prev_nulos_precio   = ventas['precio'].isna().sum() # comprueba si hay nulos, y en caso de que haya los suma
prev_nulos_cantidad = ventas['cantidad'].isna().sum() # comprueba si hay nulos, y en caso de que haya los suma
prev_dup            = ventas.duplicated().sum() # comprueba si hay duplicados, y en caso de que haya los suma

print("----Antes de limpiar Ventas----")
print("shape:", prev_shape,
      "\n  nulos precio:", prev_nulos_precio,
      "\n  nulos cantidad:", prev_nulos_cantidad,
      "\n  duplicados:", prev_dup)

# ----1° paso: Normalizar el precio (de string a float)----
if 'precio' in ventas.columns: # me aseguro que la columna precio este en el df ventas
  ventas['precio'] = (
      ventas['precio']
      .astype(str) # convierto los valores de esta columna a str (texto)
      .str.replace(r'[$,\s]', '', regex=True) # elimino símbolos de moneda, comas, espacios
      .replace({'nan': np.nan}) # reemplaza el nan (en formato de texto) a el NaN de numpy (representa un valor nulo)
      )
  ventas['precio'] = pd.to_numeric(ventas['precio'], errors='coerce') # convierte la cadena de texto ya limpia a formato de numero

# ----- 2° paso: Convertir fechas en "ventas" y "marketing"----
# if 'fecha_venta' in ventas.columns:
 # ventas['fecha_venta'] = pd.to_datetime(ventas['fecha_venta'], dayfirst=True, errors='coerce')
#for col in ['fecha_inicio', 'fecha_fin']:
 #   if col in marketing.columns:
  #      marketing[col] = pd.to_datetime(marketing[col], dayfirst=True, errors='coerce')

# Conversión de fechas
if 'fecha_venta' in ventas.columns: # # me aseguro que la columna fecha_venta este en el df ventas
    ventas['fecha_venta'] = pd.to_datetime(ventas['fecha_venta'], dayfirst=True, errors='coerce') # convierte los valores de esta columna a tipo fecha tipo dd/mm/aa.
                                                                                                  # coerse fuerza que, si hay algún valor inválido (por ejemplo, texto que no parece fecha), Pandas lo convierta en NaT (Not a Time, equivalente a NaN pero para fechas).

for col in ['fecha_inicio', 'fecha_fin']: # bucle que recorre las columnas fecha_inicia y fecha_fin
    if col in marketing.columns: #verifico si la columna existe en el df marketing
        marketing[col] = pd.to_datetime(marketing[col], dayfirst=True, errors='coerce') #Convierte cada columna encontrada (fecha de inicio y fecha de fin de campaña) a tipo datetime, igual que antes.

# Verificación rápida
print("Resumen de conversiones:")
if 'fecha_venta' in ventas.columns:
    print(f"NaT en fecha_venta: {ventas['fecha_venta'].isna().sum()}") # si encuentra NaT en ventas, lo suma.

for col in ['fecha_inicio', 'fecha_fin']:
    if col in marketing.columns:
        print(f"NaT en {col}: {marketing[col].isna().sum()}") # si encuentra NaT en marketing, lo suma.

# ---- 3° paso:Eliminar filas con nulos críticos en "ventas"----
mask_validos = ventas['precio'].notna() & ventas['cantidad'].notna() # me devuelve un valor de tipo booleano (true) si el valor no es nulo
eliminados_nulos = (~mask_validos).sum() # el ~ convierte en lo contrario los valores booleanos (de true a false y viceversa).
                                         # marca las filas que tienen al menos un nulo. suma los valores true.
                                         # guarda cuántas filas con valores nulos fueron detectadas y eliminadas.
print("Eliminados por nulos:", eliminados_nulos)
ventas = ventas[mask_validos].copy() # Usa la máscara para quedarse solo con las filas válidas (las que no tienen nulos en precio ni en cantidad). el .copy sirve para hacer una copia del df
                                     # asi no se pierde el df original

# ----4° paso: Elimino duplicados exactos en ventas----
tamano_antes = len(ventas) # el tamaño del df antes de eliminar los duplicados
ventas = ventas.drop_duplicates().copy() # creo un nuevo df con los valores duplicados eliminados
tamano_despues = len(ventas) # tamaño del df despues de la eliminacion de dupliados
dup_eliminados = tamano_antes - tamano_despues
print("Duplicados eliminados:", dup_eliminados)

# ----5° paso: Creo columna importe para uso posterior----
ventas['importe'] = ventas['precio'] * ventas['cantidad']

# ----6° paso: post-limpieza----
post_shape = ventas.shape
post_nulos_precio   = ventas['precio'].isna().sum()
post_nulos_cantidad = ventas['cantidad'].isna().sum()
post_dup            = ventas.duplicated().sum()

print("----Después de limpiar Ventas----") # muestro que se eliminaros los nulos y duplicados
print("shape:", post_shape,
      "| nulos precio:", post_nulos_precio,
      "| nulos cantidad:", post_nulos_cantidad,
      "| duplicados:", post_dup)

# ----7° paso: Vista rápida----
print("\nChequeo rápido (post-limpieza):")
print("\nnulos importe:", ventas['importe'].isna().sum())
print("\nrango fechas ventas:", ventas['fecha_venta'].min(), "a", ventas['fecha_venta'].max())

# Vista mínima
display(ventas.head(5))

"""# Justificación del codigo de "Limpieza de Datos"
Antes de comenzar con la limpieza de los datos, realicé un control previo sobre el dataset de ventas para registrar el estado inicial. Analicé el tamaño del DataFrame (shape), la cantidad de valores nulos en las columnas precio y cantidad, y el número de filas duplicadas. Este paso me permitió tener una referencia clara para luego comparar los resultados obtenidos después de la limpieza.

En primer lugar, normalicé la columna precio, ya que contenía valores en formato texto. Eliminé símbolos de moneda, comas y espacios para convertir los datos a formato numérico (float), asegurando que los cálculos posteriores se realicen correctamente.

Luego, convertí las fechas presentes en ambos datasets: fecha_venta en el DataFrame de ventas, y fecha_inicio y fecha_fin en el de marketing. Utilicé pd.to_datetime() con el parámetro dayfirst=True para asegurar que el formato de fecha se interpretara correctamente (día/mes/año) y que los valores no válidos se convirtieran en NaT (nulos de tipo fecha).

Después, apliqué una limpieza general de texto en las columnas categóricas (de tipo object), eliminando caracteres especiales y espacios innecesarios al inicio y al final. Esto permitió estandarizar los nombres de productos, categorías y clientes, evitando errores en la integración o en los filtros posteriores del análisis.

A continuación, eliminé las filas con valores nulos críticos en las columnas precio y cantidad, ya que ambas son variables fundamentales para calcular el importe total de cada venta. También removí las filas duplicadas, garantizando que cada registro fuera único dentro del conjunto de datos.

Como paso siguiente, generé una nueva columna llamada importe, calculada como el producto entre precio y cantidad. Esta variable resultó clave para los análisis económicos y métricas de desempeño posteriores.

Finalmente, elaboré un reporte posterior a la limpieza, donde comparé el tamaño del DataFrame antes y después del proceso, así como la cantidad de valores nulos y duplicados eliminados. También verifiqué los rangos de fechas para asegurar la consistencia temporal y revisé visualmente las primeras filas del DataFrame limpio.

En conclusión, tras este proceso de limpieza, el conjunto de datos quedó sin duplicados, sin caracteres no deseados, con las fechas correctamente parseadas y con las columnas principales en el formato adecuado.

# De vuelta al orden original
## Etapa 1: Actividad 2
Realizar un script básico que calcule las ventas mensuales utilizando
variables y operadores.
"""

# Script básico que calcula las ventas mensuales


# Aseguro que exista la columna 'importe'
if 'importe' not in ventas.columns:
    ventas['importe'] = ventas['precio'] * ventas['cantidad']

# Creo un diccionario acumulador
totales = {} # esto servira como acumulador donde se iran guardando las ventas totales por año y mes

# Contadores de control
procesadas = 0 # cuenta cuantas filas validas de analizan
omitidas = 0 # cantidad de filas saltadas por datos faltantes

# Recorro el DataFrame fila por fila
for fila in ventas.itertuples(index=False): # recorre le df fila por fila
    fecha = fila.fecha_venta
    importe = fila.importe

 # Valido que la fila tenga datos válidos
    if pd.isna(fecha) or pd.isna(importe): # si hay valores nulos el contador omitidos se incrementa en 1
        omitidas += 1
        continue

    año = fecha.year # a partir del objeto datatime, extraigo el año y mes
    mes = fecha.month # creoclave única combinando ambos valores (año, mes).

    clave = (año, mes) #Esa clave servirá para agrupar las ventas del mismo mes y año.

    # Acumulo los importes por (año, mes)
    if clave in totales:          # Si la clave (año, mes) ya existe en el diccionario totales, se le suma el importe de la fila actual.
        totales[clave] += importe
    else:
        totales[clave] = importe # Si no existe, se crea una nueva entrada con el importe inicial.

    procesadas += 1              # se incrementa el contador de procesadas.

# Ordeno las claves (año, mes)
totales_ordenados = dict(sorted(totales.items())) # el sorted () sirve para ordenar el diccionario por sus claves, haciendo que aparezcan cronologicamente

# Muestro los resultados
print("---- Ventas mensuales ---- \n")
for (año, mes), total in totales_ordenados.items():
    print(f"{año}-{mes:02d}: ${total:,.2f}") # el :02d es para que sean con dos digitos y :,.2f formatea el número con comas para miles y dos decimales.

print("\n---- Resumen ----")
print("Filas procesadas:", procesadas)
print("Filas omitidas por datos faltantes:", omitidas)

"""# Etapa 1: Actividad 3
Estructuras de Datos: Desarrollar un programa que almacene los datos de
ventas (producto, precio, cantidad). Decidir si conviene utilizar diccionarios o
listas.
"""

# ----Creo una lista vacía donde voy a guardar cada registro de venta----
registros = [] # aqui se guardaran todas las ventas. cada ventase representará con un diccionario individual,
               # que contendrá las claves "producto", "precio" y "cantidad". seria una lista de diccionarios

# Recorro el DataFrame fila por fila
for fila in ventas.itertuples(index=False): # permite recorrer cada fila del DataFrame ventas. uso index_false para omitir el indice

# Armo un diccionario con los datos que quiero guardar
    registro = {
        "producto": fila.producto,                 # nombre del producto
        "precio": float(fila.precio),              # lo convierto a número decimal
        "cantidad": float(fila.cantidad)           # lo convierto a número decimal
    }

# Agrego ese diccionario a la lista general
    registros.append(registro) # Cada diccionario creado se agrega al final de la lista registros.

# ----Resultado----

# Muestro los primeros 10 registros para verificar
print("Registros guardados:")
for r in registros[:10]:
    print(r)

# Compruebo cuántas ventas se guardaron
print("\nTotal de registros almacenados:", len(registros))

"""# Etapa 2: Actividad 2
Transformación de Datos: Aplicar filtros y transformaciones para crear una
tabla de ventas que muestre solo los productos con alto rendimiento.
* Elegí filtrar los productos por encima del promedio de todos los ingresos
"""

# ----Paso 1: Calcular ingresos totales por producto----

# Creé un diccionario acumulador: clave = producto, valor = ingresos totales
ingresos_por_producto = {}

for fila in ventas.itertuples(index=False): # Recorro el df fila por fila. En cada iteración, se extraen los valores de las columnas producto e importe de la fila actual.
    producto = fila.producto
    importe = fila.importe

    if pd.isna(producto) or pd.isna(importe):
        continue  # hago una validación de calidad de datos. omito filas inválidas. si es NaN omito esa fila y paso a la siguiente

    if producto in ingresos_por_producto: # Si el producto ya existe como clave en el diccionario, se suma su nuevo importe al total acumulado.
        ingresos_por_producto[producto] += importe
    else:                                 # Si es la primera vez que aparece ese producto, se crea la clave y se le asigna el importe inicial.
        ingresos_por_producto[producto] = importe

# ----Paso 2: Convertir a DataFrame para filtrar y ordenar----

tabla_ingresos = pd.DataFrame( # convierto el diccionario a una lista de tuplas (producto, total) para poder transformarlo fácilmente en un DataFrame de Pandas.
    [(prod, total) for prod, total in ingresos_por_producto.items()],
    columns=['producto', 'ingresos_totales']
)

# Se ordena de mayor a menor
tabla_ingresos = tabla_ingresos.sort_values(by='ingresos_totales', ascending=False) #los productos con mayores ventas aparecen primero.

# ----Paso 3: Filtrar productos de alto rendimiento----

# Considero "alto rendimiento" los que tienen ingresos > promedio
promedio_ingresos = tabla_ingresos['ingresos_totales'].mean() #Calculo el promedio general de ingresos (mean()).
tabla_alto_rendimiento = tabla_ingresos[tabla_ingresos['ingresos_totales'] > promedio_ingresos]


# ----Paso 4: Mostrar resultados----

print("---- Productos de alto rendimiento ----")
display(tabla_alto_rendimiento)

"""# Etapa 2: Actividad 3
Agregación: Resumir las ventas por categoría de producto y analizar los
ingresos generados.
"""

# ----Paso 1: Agrupar y resumir por categoría----

resumen_cat = (
    ventas.groupby('categoria', as_index=False)
          .agg(
              ingresos=('importe', 'sum'),        # se suma dinero por categoría
              unidades=('cantidad', 'sum'),       # se suma unidades vendidas
              transacciones=('id_venta', 'count') # cantidad de ventas
          )
          .sort_values('ingresos', ascending=False) # orden de mayor a menor ingresos
)

# ----Paso 2: Calcular participación % sobre el total----

total_ingresos = resumen_cat['ingresos'].sum() # calculo la suma total de ingresos
resumen_cat['participacion_%'] = (resumen_cat['ingresos'] / total_ingresos * 100).round(2) # porcentaje que representa cada categoria y con el .round(2) lo redondea a dos digitos

# ----Paso 3: Calcular ticket promedio por transacción----

resumen_cat['ticket_promedio'] = (resumen_cat['ingresos'] / resumen_cat['transacciones']).round(2)

# ----Paso 4: Mostrar resultado----

print("---- Resumen de ventas por categoría ----")
display(resumen_cat)

"""# Etapa 2: Actividad 4
Integración de Datos: Combinar los sets de datos de ventas y marketing
para obtener una visión más amplia de las tendencias.
"""

# Paso previo: Revisar si estan las columnas
print("Columnas en ventas:", ventas.columns.tolist())
print("Columnas en marketing:", marketing.columns.tolist())

# ----Paso 1: Merge usando la columna 'producto' como clave----

ventas_marketing = pd.merge( # combino dos DataFrames basándose en una columna clave
    ventas,
    marketing,
    on='producto',         # esta columna esta en ambos dataset
    how='left',            # mantengo todas las filas de ventas
    suffixes=('_venta', '_marketing') # Sirve para evitar confusiones cuando hay columnas con el mismo nombre en ambos DataFrames.
)

# ----Paso 2: Revisar resultado----

print("\n ---- Vista rápida del dataset combinado ----")
print("\n Shape combinado:", ventas_marketing.shape)
display(ventas_marketing.head(5))